[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_template"
description = "Template Python repository"
dynamic = ["version"]
readme = { file = "README.rst", content-type = "text/x-rst" }
license = { file = "LICENSE.rst", content-type = "text/plain" }
authors = [
  { name = "Jeff Jennings", email = "jjennings@flatironinstitute.org" },
]
requires-python = ">=3.10"
dependencies = ["numpy>=1.24"]